version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - /var/www/html/vendor
      - /var/www/html/var
      - ./:/var/www/html
  db:
    image: mariadb:latest
    volumes:
      - mysqldata:/var/lib/mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: root
      MARIADB_DATABASE: dockertest
    restart: always
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:dockertest
      - MYSQL_USERNAME:user
      - MYSQL_ROOT_PASSWORD:root
    depends_on:
      - db

volumes:
  mysqldata:
